// --------------------------------------------------
// Native functions
// --------------------------------------------------
//Gamemode related
	
// Player related
native HasClientSpawned(playerid);
native GetPlayerDeaths(playerid);
native GetPlayerKills(playerid);
native IsClientConnected(playerid);
native SetPlayerHealth(playerid, health);
native GetPlayerHealth(playerid);
native EyeAngles(playerid, &Float:x, &Float:y, &Float:z );